/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.ClassAdministrador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class Administrador extends javax.swing.JFrame implements ActionListener{
private ClassAdministrador Admin;
private Socket socket;
public static final String VALIDARADMIN ="ValidarAdmin";

    public Administrador(Socket soc) {
        initComponents();
        Admin = new ClassAdministrador();
        this.setLocationRelativeTo(null);// PAra centrar la vista
        socket=soc;
        btnValidarAdmin.setActionCommand(VALIDARADMIN);
        btnValidarAdmin.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        campoPassword = new javax.swing.JPasswordField();
        btnValidarAdmin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JlabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });
        getContentPane().add(campoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, 30));
        getContentPane().add(campoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 170, 30));

        btnValidarAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnValidarAdmin.setForeground(new java.awt.Color(0, 0, 204));
        btnValidarAdmin.setText("GO");
        btnValidarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JlabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/technology-wallpapers-hd-resolution-On-wallpaper-hd.jpg"))); // NOI18N
        JlabelFondo.setMaximumSize(new java.awt.Dimension(500, 600));
        JlabelFondo.setMinimumSize(new java.awt.Dimension(500, 600));
        JlabelFondo.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(JlabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnValidarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarAdminActionPerformed
        
    }//GEN-LAST:event_btnValidarAdminActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       new Interfas(socket).setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFondo;
    private javax.swing.JButton btnValidarAdmin;
    private javax.swing.JTextField campoID;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent evento) {
        String usuario= campoID.getText();
        char[] contrasenia = campoPassword.getPassword();
  
         if(evento.getActionCommand().equals(VALIDARADMIN)){
               try {   if(Admin.validarAdministrador(usuario, contrasenia)){
            InterfasEditor inicioAdmin = new InterfasEditor(socket);
            inicioAdmin.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Contrasenia o usuario incorrecto","Inicio Sesion",JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
       JOptionPane.showMessageDialog(this, e.getMessage(),"Inicio Sesion",JOptionPane.ERROR_MESSAGE);
    }
         }
     
    }
}
