/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Editor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class InterfasEditor extends javax.swing.JFrame implements ActionListener {
public static final String CREAR ="Crear";
public static final String ABRIR ="Abrir";
public static final String GUARDAR ="Guardar";
public static final String ELIMINAR="Eliminar";
public static final String REGRESAR ="Regresar";
private Socket socket;
private final Editor editor;
/**
     * Creates new form InterfasEditor
     */
    public InterfasEditor(Socket soc) {
        initComponents();
        this.setLocationRelativeTo(null);
        socket=soc;
        
        editor = new Editor();
        
        btnAbrir.setActionCommand(ABRIR);
        btnAbrir.addActionListener(this);
        
        btnCrear.setActionCommand(CREAR);
        btnCrear.addActionListener(this);
        
        btnGuardar.setActionCommand(GUARDAR);
        btnGuardar.addActionListener(this);
        
        btnEliminar.setActionCommand(ELIMINAR);
        btnEliminar.addActionListener(this);
        
        btnRegresar.setActionCommand(REGRESAR);
        btnRegresar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAcciones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        PanelEdicion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEdicion = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de archivos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAcciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setText("Crear Archivo");
        PanelAcciones.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 140, -1));

        btnGuardar.setText("Guardar Archivo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        PanelAcciones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 150, -1));

        btnAbrir.setText("Abrir Archivo");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        PanelAcciones.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        btnEliminar.setText("Eliminar Archivo");
        PanelAcciones.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 130, -1));

        getContentPane().add(PanelAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 540, -1));

        PanelEdicion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taEdicion.setColumns(20);
        taEdicion.setRows(5);
        jScrollPane1.setViewportView(taEdicion);

        PanelEdicion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 180));

        getContentPane().add(PanelEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, 619, 180));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/technology-wallpapers-hd-resolution-On-wallpaper-hd.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
                                             
    
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirActionPerformed
    
    public String darContenido(){
       return  taEdicion.getText();
    }
    
   
    public void eliminarArchivo(){
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            String contenido ="";
            f.delete();
            JOptionPane.showMessageDialog(this,"Archivo eliminado con exito ","Editor de archivos",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void abrirArchivo(){
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            String contenido ="";
            try {
               contenido =  editor.abrirArchivo(f.getAbsolutePath());
                taEdicion.setText(contenido);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(),"Editor Simple de Archivos",JOptionPane.ERROR_MESSAGE);
                 }
        } 
        
    }
    /*
    public void refrescarContenido(String contenido){
        taEdicion.setText(contenido);
    }
    
*/
    public void crearArchivo(){
     editor.crearArchivo();
     String contenido="";
     taEdicion.setText(contenido);
    }
    
    public void guardarArchivo(){
        String contenido="";
        String rutaArchivo="";
        
        if(editor.esArchivoNuevo()){
            JFileChooser fc = new JFileChooser();
            if (fc.showSaveDialog(this)== JFileChooser.APPROVE_OPTION){
                rutaArchivo = fc.getSelectedFile().getAbsolutePath();
               
            }
        }
         contenido = taEdicion.getText();
                try {
                    editor.guardarArchivo(contenido, rutaArchivo);
                    JOptionPane.showMessageDialog(this,"Archivo guardado con exito ","Editor de archivos",JOptionPane.INFORMATION_MESSAGE);
         
                } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(),"Editor Simple de Archivos",JOptionPane.ERROR_MESSAGE);
                    
                }
                
    }
    
    
    
  
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAcciones;
    private javax.swing.JPanel PanelEdicion;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taEdicion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent evento) {
       if(evento.getActionCommand().equals(ABRIR)){  
           abrirArchivo();
        }else if(evento.getActionCommand().equals(CREAR)){
                   crearArchivo();
                   }else if(evento.getActionCommand().equals(GUARDAR)){
                       guardarArchivo();
                        }else if(evento.getActionCommand().equals(ELIMINAR)){
                       eliminarArchivo();
                        }else if(evento.getActionCommand().equals(REGRESAR)){
                            this.setVisible(false);
                             new Administrador(socket).setVisible(true);
                        }
         }
}
